version: "3.5"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.6-32.0
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.hostname==node1"
    ports:
      - target: 389
        published: 389
        protocol: tcp
        mode: host
    environment:
      LDAP_URLS: "ldap://ldap1/"
      LDAP_REPLICATION_HOSTS: "ldap://ldap1/ ldap://ldap2/"
      LDAP_EXTRA_HOST: "ldap1"
      LDAP_EXTRA_HOST_IP_PREFIX: "172.18.0."
    extra_hosts:
      - "ldap2:10.101.216.76"
    volumes:
      - /var/local/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /var/local/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
  mariadb:
    image: mariadb:10.10.2
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.hostname==node1"
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    command:
      - "--log-bin"
      - "--log-basename=node1"
      - "--server-id=1"
      - "--replicate-do-db=keycloak"
      - "--auto_increment_increment=2"
      - "--auto_increment_offset=1"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/mysql:/var/lib/mysql
  keycloak:
    image: dcm4che/keycloak:23.0.7
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.hostname==node1"
    ports:
      - target: 8843
        published: 8843
        protocol: tcp
        mode: host
      - target: 7600
        published: 7600
        protocol: tcp
        mode: host
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeit
      KC_HTTPS_PORT: 8843
      KC_HOSTNAME: node1
      KC_DB: mariadb
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: mariadb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_LOG: file
      KC_LOG_LEVEL: INFO,org.infinispan:DEBUG,org.jgroups:DEBUG
      KC_CACHE_CONFIG_FILE: cache-ispn-jdbc-ping.xml
      JGROUPS_DISCOVERY_EXTERNAL_IP: 10.101.216.136
      JGROUPS_BIND_IP_PREFIX: 172.18.0.
      KEYCLOAK_WAIT_FOR: ldap:389 mariadb:3306
    extra_hosts:
      - "ldap:10.101.216.136"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/keycloak:/opt/keycloak/data
