version: "3"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.6-32.0
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_URLS: ldap:/// ldaps:///
    volumes:
      - /var/local/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /var/local/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
  keycloak:
    image: dcm4che/keycloak:23.0.7
    ports:
      - "8843:8843"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeit
      KC_HOSTNAME: gunter-nb
      KC_HTTPS_PORT: 8843
      KC_LOG: file
      ARCHIVE_HOST: gunter-nb
      ARCHIVE_MANAGEMENT_HOST: gunter-nb
      KIBANA_CLIENT_ID: kibana
      KIBANA_CLIENT_SECRET: changeit
      KIBANA_REDIRECT_URL: https://gunter-nb:8643/oauth2/callback/*
      KEYCLOAK_WAIT_FOR: ldap:389
    depends_on:
      - ldap
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/keycloak:/opt/keycloak/data
      - /var/local/dcm4chee-arc/keycloak-themes:/opt/keycloak/themes
