services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.7-33.1
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_URLS: ldap:/// ldaps:///
    volumes:
      - /var/local/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /var/local/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
  keycloak:
    image: dcm4che/keycloak:26.0.6
    ports:
      - "8843:8843"
      - "8788:8788"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: changeit
      KC_HOSTNAME: https://shefki-lifebook:8843
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: 'true'
      KC_HTTPS_PORT: 8843
      KC_LOG: file
      ARCHIVE_HOST: gunter-nb
      KIBANA_CLIENT_ID: kibana
      KIBANA_CLIENT_SECRET: changeit
      KIBANA_REDIRECT_URL: https://shefki-lifebook:8643/oauth2/callback/*
      KEYCLOAK_WAIT_FOR: ldap:389
      DEBUG: 'true'
      DEBUG_PORT: '*:8788'
      KC_SPI_THEME_STATIC_MAX_AGE: -1
      KC_SPI_THEME_CACHE_THEMES: 'false'
      KC_SPI_THEME_CACHE_TEMPLATES: 'false'
    depends_on:
      - ldap
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/keycloak:/opt/keycloak/data
      - /var/local/dcm4chee-arc/keycloak-themes:/opt/keycloak/themes
