version: "3.5"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.6-32.0
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.hostname==gunter-nb"
    ports:
      - target: 389
        published: 389
        protocol: tcp
        mode: host
      - target: 636
        published: 636
        protocol: tcp
        mode: host
    environment:
      LDAP_URLS: ldap:/// ldaps:///
    volumes:
      - /var/local/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /var/local/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
  mariadb:
    image: mariadb:10.10.2
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.hostname==gunter-nb"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/mysql:/var/lib/mysql
  keycloak:
    image: dcm4che/keycloak:23.0.6
    ports:
      - "8843:8843"
      - "8787:8787"
    environment:
      ARCHIVE_HOST: gunter-nb
      LDAP_URL: ldaps://ldap:636
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeit
      KC_HTTPS_PORT: 8843
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME: gunter-nb
      KC_DB: mariadb
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: mariadb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_LOG: file
      KC_LOG_LEVEL: INFO
      DEBUG: "true"
      KEYCLOAK_WAIT_FOR: ldap:389 mariadb:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/keycloak:/opt/keycloak/data
      - /var/local/dcm4chee-arc/keycloak-themes:/opt/keycloak/themes
